### ISSUE TITLE
error logs in fabricator-assemble

### ISSUE THREAD

**Issue by lmolema** [fbrctr/fabricator-assemble#1]
Is there a way to see in the error log which file or line of code causes the assemble task to fail? Would be a very useful enhancement imho.

**Comment by paulrobertlloyd** [comment]
+1 Got in to all sorts of issues running fabricator; turned out all I was doing was calling a component that no longer existed.

**Comment by LukeAskew** [comment]
Working on this. What kind of errors do you think would be helpful to catch? So far I have:

1. Front-matter YAML parsing errors
2. Handlebars parsing errors (syntax and missing fields)

**Comment by LukeAskew** [comment]
@lmolema @paulrobertlloyd @aputinski Checkout #5 if you get a chance.
