### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by Yago** [fbrctr/fabricator-assemble#14]
@LukeAskew Is it possible to publish a new release ? Because it's not really clean to call the master branch in our `package.json` :sweat_smile:

**Comment by LukeAskew** [comment]
Sure thing. Just published `v1.1.6`

Sorry for the delay, just got back from some vacation. Here's a photo!

![Red River Gorge](https://lh3.googleusercontent.com/nji2GxDHL128d0iHbc9hfV-kmHNn4v3HX7d1pE9YjHo=w1440-h431-no)

**Comment by Yago** [comment]
Wow, seems nice !

Thanks anyway :smile::+1:
