### ISSUE TITLE
Add ability to use .hbs files

### ISSUE THREAD

**Issue by dietergeerts** [fbrctr/fabricator-assemble#18]
When working with a toolkit, it's easier to use .hbs files as intellij can then use the handlebars plugin. But fabricator-assemble only accepts .html files. I would like too see the usage of both.

**Comment by LukeAskew** [comment]
Check out the PR. Does that do the trick for you?

Currently, the fabricator-assemble doesn't care about the extension - the glob pattern grabs everything. Just needed to rename the extension to `.html` when writing the file.

**Comment by dietergeerts** [comment]
Thx! Sorry I couldn't get to it faster.
