### ISSUE TITLE
assemble output going into /dist/src/views/

### ISSUE THREAD

**Issue by visualjazz-skinread** [fbrctr/fabricator-assemble#2]
Hi, I've been loving working with fabricator and have scaffolded a new project with the latest generator.

Have noticed that the assemble task is placing output in /dist/src/view, and in the context of running fabricator, the only localhost output in the browser is `Cannot GET /`

Was wondering if an issue might have been introduced recently. Supplying a config param with the output folder still contained the output in src/views/.

**Comment by visualjazz-skinread** [comment]
Have traced the issue on my windows box and it seems to be that path.dirname is returning `/` as a directory separator while path.sep has a value mismatch of `\` causing the string split on line 486 of index.js to contain full path in the array.

Same issue seen on another windows workstation. I'll investigate as a node issue..

**Comment by LukeAskew** [comment]
Thanks for finding this. Just patched a fix. :+1: if you could verify.

**Comment by visualjazz-skinread** [comment]
Cheers! I've created a pull request with a few other instances path.dirname patched for windows as well if you'd like to use. Creates the correct output now on my local.
New materials structure is exactly what I needed.
