### ISSUE TITLE
Menu hierarchy incorrect on 1.1.8 

### ISSUE THREAD

**Issue by jackappleby** [fbrctr/fabricator-assemble#23]
I have filtered what kind of files are shown in Fabricator in the materials directory. i.e.

```javascript
gulp.task('assemble', function (done) {
	assemble({
		logErrors: config.dev,
		materials: 'src/materials/**/*.html'
	});
	done();
});
```

This is because I am grouping my CSS, JS and HTML into folders within the materials folder but don't want CSS and JS files to be outputted into the Fabricator pages. 

Using version 1.1.7 this worked, but on 1.1.8 the menu structure outputs my HTML files ungrouped. i.e.:

<img width="202" alt="screen shot 2015-09-02 at 11 21 31" src="https://cloud.githubusercontent.com/assets/1742659/9628705/ec76837c-5164-11e5-90ee-47ff3f3ff358.png">

It should look like  more like this:

<img width="194" alt="screen shot 2015-09-02 at 11 23 26" src="https://cloud.githubusercontent.com/assets/1742659/9628718/131ebe9a-5165-11e5-8855-4b50cecf393d.png">

Any ideas?

**Comment by LukeAskew** [comment]
Seems like an issue with the way I was using the glob pattern to identify parent directories.

Just pushed some changes to the `dir-glob` branch that might fix the issue. Mind checking it out and giving it a test?

**Comment by jackappleby** [comment]
Thanks a lot Luke, seems to have done the trick! The menu hierarchy is correct.
