### ISSUE TITLE
Folder naming conventions

### ISSUE THREAD

**Issue by talldan** [fbrctr/fabricator-assemble#25]
We just had an issue with building our pattern library. It was caused by a developer creating a folder with a space in materials/molecules:
'notification bars'

Looking at the code, it looks as though fabricator-assemble only supports folder names with hyphens (when combined with using ordering on partial in a sub-collection):
'notification-bars'

That's all good - I wonder if it's worth documenting this restriction - I had a look through the readme and couldn't see it mentioned anywhere.

For your info, this is the regular expression that causes this restriction (index.js:553). If a template has both a space in the folder name and a leading number, the leading number isn't stripped out:
```javascript
var key = name.replace(/^([a-z][a-z0-9\-]*\.)?([0-9\.-]+)(.*)$/i, '$1$3');
```

**Comment by LukeAskew** [comment]
Thanks for reporting this.

I wonder if it would be helpful to allow spaces in folder and file names. Spaces would need to be converted to dashes internally (so that things like partials and url hashes work correctly), but allowing spaces would give devs more flexibility project setup.

**Comment by talldan** [comment]
It could be useful. I'm sure others might stumble upon this issue, and people don't always spot things in documentation.
