### ISSUE TITLE
Allow callback functionality

### ISSUE THREAD

**Issue by sethlopezme** [fbrctr/fabricator-assemble#27]
I think it would be incredibly useful to allow the user to provide a callback to the `assemble` function which gets called when `assemble` is finished executing.

Example:
```js
// let config = { ... };
assemble(config, () => {
    console.log('complete');
});
```

This would be especially useful in situations where something must happen after `assemble` is _completely_ finished, such as a build task.

**Comment by LukeAskew** [comment]
The `assemble()` task is synchronous, so you can just call your function immediately after.
