### ISSUE TITLE
JSON files inside "views" folder getting converted to HTML

### ISSUE THREAD

**Issue by BillClarkFC** [fbrctr/fabricator-assemble#37]
Hello,

We're experiencing kind of a strange issue. Inside the "views" folder we have a "services" folder with a few .json files in it. They're being referenced via AJAX. Upon running fabricator-assemble, these files are being converted to HTML files in our compiled "dist" folder. We are using a layout for these JSON files that simply consists of `{% body %}` Any thoughts on how we can get these to remain JSON files upon compiling? Or are all files in the "views" folder treated as HTML only? Thanks!

**Comment by LukeAskew** [comment]
The assembler assumes the files are html/handlebars. You might consider storing this json files in a different directory.

Often, I like to carry my `src/data` folder through to `dist` so I can hit those files as a mock API. To do so, I just add a task to the `gulpfile`:

```
import yml from 'gulp-yml';

// save out data as JSON
gulp.task('data', function () {
	return gulp.src('src/data/**/*')
		.pipe(yml().on('error', gutil.log))
		.pipe(gulp.dest(config.dest + '/data'));
});
```

You could do that same with a different folder name if you wanted to keep these view json files separated from `data`.

**Comment by BillClarkFC** [comment]
Thanks so much, Luke!
