### ISSUE TITLE
subfolder limit?

### ISSUE THREAD

**Issue by kuschti** [fbrctr/fabricator-assemble#38]
Is there a way to have more subfolders (levels) in materials? Or, if not, can you help me and tell me where i can change myself?

Now I have the following structure:
```
└── materials
    ├── atoms
    │   └── buttons
    │       ├── default.html
    │       └── sizes.html
    └── molecules
```

Structure i need (1 or more levels):
```
└── materials
    ├── group1
    │   └── atoms
    │       └── buttons
    │           ├── default.html
    │           └── sizes.html
    └── group2
```

**Comment by LukeAskew** [comment]
There is not currently, but I have the functionality slated for future versions.

**Comment by kuschti** [comment]
ok, thanks for your answer!
