### ISSUE TITLE
Option to use alternative taxonomy for API

### ISSUE THREAD

**Issue by paulrobertlloyd** [fbrctr/fabricator-assemble#4]
It would be great if alternative names could be used in place of Fabricator terms, i.e. materials could be named components or partials instead. Currently, it is only possible to change the name of the folder these terms relate to, but in templates, the terms Fabricator understands still need to be used.

(Materials seems most problematic, as it’s a new term that relates only to Fabricator. A more generic/common term for this construct might be more widely understood).

**Comment by LukeAskew** [comment]
I'll have to put some thought into this.

Is the desire to have ability to access the `material` hash in templates using a different keyword? e.g.
`materials.items` => `partials.items` ?

The challenge is that a user can store "materials" anywhere; they are not restricted to a single directory. For example, a user could pass these options to the `assemble()` task:

```javascript
// assemble
gulp.task('assemble', function (done) {
    assemble({
        materials: ['src/components/**/*', 'src/widgets/**/*']
    });
    done();
});
```

The html files found be each glob would get parsed and stored in `materials.items`.

This flexibility means that the `materials` keyword can't be inferred from the directory name, but has to be explicitly defined if made configurable.

Does a new option like `materialKey: <String>` make sense?

**Comment by paulrobertlloyd** [comment]
Bingo! `materialKey` sounds perfect. :-)

**Comment by LukeAskew** [comment]
@paulrobertlloyd checkout #6
